name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  build-backend:

    runs-on: ubuntu-latest
    environment: webdock vps
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    defaults:
      run:
        working-directory: ./back
    steps:

      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
#      - name: Add ssh key to agent
#        uses: webfactory/ssh-agent@v0.7.0
#        with:
#          ssh-private-key: ${{ secrets.SSHKEY }}
#          ssh-auth-sock: 22
#          log-public-key: false
        
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.HOSTNAME }}
          username: ${{ vars.USERNAME }}
          port: ${{ vars.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "/home/runner/work/genealogy/genealogy/back/Genealogy/bin/Release/net6.0/*"
          target: "~/temp"
